### ISSUE TITLE
Grommet switch

### ISSUE THREAD

**Issue by jimwhurr** [dimitropoulos/react-ui-roundup#16]
Grommit does not have a component called Switch but using CheckBox  with the toggle prop is visually presented as a switch, e.g.
`<CheckBox toggle>`

**Comment by dimitropoulos** [comment]
thanks!  I added it in here https://github.com/dimitropoulos/react-ui-roundup/commit/cb6747ae160006afda13acdcd89b44a325340cd3

Let me know if I didn't get it 100% right :)
