### ISSUE TITLE
[Select] - add virtualization Criteria to the select

### ISSUE THREAD

**Issue by ItayTur** [dimitropoulos/react-ui-roundup#29]
virtualization support is a key feature, when having dropdown lists with multiple options. adding this criteria can be really helpful.

**Comment by dimitropoulos** [comment]
great suggestion! sorry I didn't see this until right now, but it's been added by https://github.com/dimitropoulos/react-ui-roundup/commit/59435156b7a969b33c102383f6aa892c4c4e6f59.

thanks!
